x=["welcome",20,"how",15,10,"blue","welcome", 12]
print(x)
print(type(x))
print(len(x))

print("welcome" in x)
print("Red" not in x)
print(x[3])
print(x[3:5])
print(x[4:])
print(x[:5])
print(x[-1])
print(x[-5:-2])
print(x[-3:])
print(x[:-4])
x[1]="walking" #change item
print(x)
x.append("hello") #adding a value
print(x)
x.insert(2,"name")
print(x)
y=["color",20,"red",10,"black"]
x.extend(y)
print(x)
x.remove("color")
print(x)
x.pop(3)
print(x)
x.pop()
print(x)
del x[2]
print(x)
# x.clear()
# print(x)
# del x
# print(x)
for i in x:
    print(i)

s=["hello","my","name","is","ram","fruit","apple","color","black","black"]
s.sort()
print(s)
s.sort(reverse=True)
print(s)
y=s.copy()
print(y)
b=list(s)
print(b)
print(s+x)
s.extend(x)
print(s)

print(s.count("black"))


z=("there","are",20,40,"many",14,"fruits",20)
print(z)
print(type(z))

print("there" in z)
print(15 not in z)
print(z[2:5])
print(z[5:])
print(z[:7])
print(z[-1])
print(z[-5:-2])
print(z[-2:])
print(z[:-6])
print("there" in z)
u=list(z)
print(u)
u.append("world")
print(u)
u.insert(3,"like")
print(u)
u.extend(s)
print(u)
v=tuple(u)
print(v)